### ISSUE TITLE
Audio.h & AudioStream.h

### ISSUE THREAD

**Issue by kd8bxp** [adafruit/nofrendo_arcada#7]
I tried to follow the tutorial on the adafruit website
https://learn.adafruit.com/nes-emulator-for-arcada/overview
And I think I have all the Arcada libraries installed, but I'm getting a compile error 
Audio.h No such file or directory, I believe I will also get a compile error for AudioStream.h 
Arduino IDE 1.8.10 
LinuxMint 19.3
Adafruit Edge Badge (using Adafruit pyBadge M4 Express SAMD51)
The UF2 file works, so I figure I'm just missing those libraries - where do I find them?
Thanks.

**Comment by sphereinabox** [comment]
At the bottom of https://learn.adafruit.com/adafruit-pybadge/arcada-libraries the page describes how to download and install the Adafruit fork of the teensy Audio library. That's probably the one you're missing.

**Comment by kd8bxp** [comment]
Sorry, I missed it the 1st time around, thanks for pointing it out. that was it, it compiles. Thanks
